# Generated by Django 2.2.7 on 2019-11-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerApp', '0002_auto_20191129_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(upload_to='uploads/')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerApp.Product')),
            ],
        ),
    ]
