# Generated by Django 2.2.7 on 2019-12-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerApp', '0003_auto_20191130_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
