# Generated by Django 2.2.7 on 2019-12-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerApp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
