# Generated by Django 2.2.7 on 2019-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerApp', '0006_auto_20191204_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
