# Generated by Django 2.2.7 on 2019-12-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerApp', '0007_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='product_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
